[auth]
users = [
    { username = "tanaka", password = "pass123" },
    { username = "sato",   password = "pass456" },
    { username = "yamada", password = "pass789" }
]


[api]
# どちらか片方、または両方設定可能
openai_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
gemini_key = "AIzaSyBOQFZM5OBPfBlKm36zy4fGgVubUh0qnpk"